parameters:
    authors_to_ignore: []
    names_to_urls: []
    package_aliases: []
    # e.g.: CS: 'CodingStandard'

    # create token here: https://github.com/settings/tokens/new
    # use in cli like: "GITHUB_TOKEN=%s vendor/bin/changelog-linker dump-merges ..."
    env(GITHUB_TOKEN): null
    github_token: '%env(GITHUB_TOKEN)%'

services:
    _defaults:
        autowire: true
        public: true

    Symplify\ChangelogLinker\:
        resource: "../src"
        exclude: "../src/{Contract,HttpKernel,DependencyInjection/CompilerPass,Exception,ChangeTree/Change.php}"

    Symplify\PackageBuilder\Yaml\ParametersMerger: ~
    Symplify\PackageBuilder\Parameter\ParameterProvider: ~
    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~

    GuzzleHttp\Client: ~
