services:
    _defaults:
        autowire: true
        public: true

    Symplify\BetterPhpDocParser\:
        resource: '../src'
        exclude: '../src/{DependencyInjection,HttpKernel,PhpDocParser/Ast/Type/*,*/*Info.php,*Info.php}'

    PHPStan\PhpDocParser\Lexer\Lexer: ~
    PHPStan\PhpDocParser\Parser\TypeParser: ~
    PHPStan\PhpDocParser\Parser\ConstExprParser: ~

    PHPStan\PhpDocParser\Parser\PhpDocParser:
        alias: 'Symplify\BetterPhpDocParser\PhpDocParser\PositionAwarePhpDocParser'
